<?php

/**
 * Class-LastActiveOnMemberList.php
 *
 * @package LastActiveOnMemberList
 * @link https://github.com/dragomano/smf-last-active-on-memberlist
 * @author Bugo <bugo@dragomano.ru>
 * @copyright 2025 Bugo
 * @license https://opensource.org/licenses/MIT The MIT License
 *
 * @version 0.2
 */

namespace Bugo;

if (! defined('SMF'))
	die('No direct access...');

/**
 * Generated by Simple Mod Maker
 */
class LastActiveOnMemberList
{
	public function hooks(): void
	{
		add_integration_function('integrate_member_context', self::class . '::memberContext#', false, __FILE__);
		add_integration_function('integrate_memberlist_buttons', self::class . '::memberlistButtons#', false, __FILE__);
	}

	public function memberContext(array &$memberContext): void
	{
		$memberContext['options']['last_login'] = $memberContext['last_login'];
	}

	public function memberlistButtons(): void
	{
		global $context, $txt;

		if (empty($context['user']['is_admin']))
			return;

		loadLanguage('LastActiveOnMemberList/');

		if (empty($context['custom_profile_fields']['columns'])) {
			$context['custom_profile_fields']['columns'] = [];
		}

		// Add virtual custom profile field
		$context['custom_profile_fields']['columns']['last_login'] = [
			'label' => $txt['last_activity'],
			'type'  => 'text',
			'bbc'   => false,
			'sort'  => [
				'down' => 'mem.last_login DESC',
				'up'   => 'mem.last_login ASC',
			],
		];

		$context['columns'] += $context['custom_profile_fields']['columns'];
	}
}
